### ISSUE TITLE
Deadlock on storage.operation or storage.rx_operation

### ISSUE THREAD

**Issue by grangej** [carambalabs/SugarRecord#288] opened 2016-09-20 04:22 UTC
I have noticed that if you run the storage.operation, or storage.rx_operation on mainThread or an existing context thread it will cause a deadlock, not sure if it possible to guard against this?

**Comment by pepibumur** [comment] 2016-09-22 20:55
@grangej could you provide more info about how to reproduce this issue?
Thanks!

**Comment by grangej** [comment] 2016-09-30 16:09
I think this is the situation (sorry for the delay, was trying to find the root cause):

In RX you have some event that is on background context , such as an RX_Fetch or such which then is flat mapped or subscribed to which then executes a new background operation such as rx_operation, even though the thread is marked "main thread" it does not seem to help (.observeOn(MainThread.Instance)) because it gets stuck on the CoreDataContextThread. Since we only ever have one background context it is never able to release the original performBlockAndWait since we are now waiting for the new performBlockAndWait from the new operation to execute.

So root cause is the fact that we are sharing a single background context for EVERY operation. 

Also this seems to only have started exhibiting its self in iOS 10+ I was not seeing this behavior in iOS 9.

The solution is to create a new serial scheduler and use that for your observeOn(s) this will allow previous core data performBlockWait to release and the new one to execute since it will return right away. 

Thoughts?

**Comment by pepibumur** [comment] 2017-04-07 13:00
Closing this one since it's duplicated https://github.com/carambalabs/SugarRecord/issues/311

**Closed by pepibumur** 2017-04-07 13:00 UTC
Labels: difficulty:moderate, status:waiting for user, type:bug
